
services:
  traefik:
    image: traefik:v3.3.4
    container_name: traefik-proxy
    ports:
      # HTTP/S routing entrypoints.
      - "80:80"
      - "443:443"
      # The dashboard that traefik sets up
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Traefik listens on the docker socket to register containers.
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/certs:/var/traefik/certs/:rw # Traefik will autogenerate a TLS cert into here.
    restart: unless-stopped

  node-app:
    build:
      context: https://Alanas-J:${GITHUB_TOKEN}@github.com/Alanas-J/personal-homepage-node-server.git
      dockerfile: Dockerfile
    container_name: node-app
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.prefix-stripper.stripprefix.prefixes=/node
      # HTTP
      - traefik.http.routers.node-http-router.entrypoints=http-entry
      - traefik.http.routers.node-http-router.rule=PathPrefix(`/node`)
      - traefik.http.routers.node-http-router.middlewares=prefix-stripper
      # HTTPS
      - traefik.http.routers.node-https-router.tls=true
      - traefik.http.routers.node-https-router.tls.certresolver=raspiresolver
      - traefik.http.routers.node-https-router.entrypoints=https-entry
      - traefik.http.routers.node-https-router.rule=Host(`raspi.alanas-j.site`) && PathPrefix(`/node`)
      - traefik.http.routers.node-https-router.middlewares=prefix-stripper
    restart: unless-stopped

  dns-sync:
    build:
      context: ./containers/route53_dns_sync
      dockerfile: Dockerfile
    container_name: route53-dns-sync
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
      - DOMAIN_NAME=raspi.alanas-j.site.
    restart: unless-stopped
