
networks:
  grafana: {}

# Persistent volumes outside of containers managed by docker engine.
volumes:
  grafana_dashboard_storage: {}
  loki_storage: {}

services:
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    volumes:
     - ./config/grafana/grafana.ini:/usr/local/etc/grafana/grafana.ini:ro
     - ./config/grafana/grafana-data-sources.yml:/etc/grafana/provisioning/datasources/ds.yaml:ro
     - grafana_dashboard_storage:/var/lib/grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Will need to either enable TLS or disable / route via traefik.
    networks:
      - grafana

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - loki_storage:/loki
      - ./config/grafana/loki-config.yml:/etc/loki/config.yaml:ro
    networks:
      - grafana

  # promtail:
  #   image: grafana/promtail:latest
  #   # volumes:
  #   #  - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     - grafana
