# Docker compose file for service container hosting without touching the rest of the stack.

networks:
  service_network: {
    external: true
  }

services:
  node-app:
    build:
      context: https://Alanas-J:${GITHUB_TOKEN}@github.com/Alanas-J/personal-homepage-node-server.git#main
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.prefix-stripper.stripprefix.prefixes=/node
      # Local HTTP
      - traefik.http.routers.local-node-http-router.entrypoints=local-http-entry
      - traefik.http.routers.local-node-http-router.rule=PathPrefix(`/node`)
      - traefik.http.routers.local-node-http-router.middlewares=prefix-stripper
      # Local HTTPS
      - traefik.http.routers.local-node-https-router.tls=true
      - traefik.http.routers.local-node-https-router.entrypoints=local-https-entry
      - traefik.http.routers.local-node-https-router.rule=PathPrefix(`/node`)
      - traefik.http.routers.local-node-https-router.middlewares=prefix-stripper
      # Internet HTTP
      - traefik.http.routers.internet-node-http-router.entrypoints=internet-http-entry
      - traefik.http.routers.internet-node-http-router.rule=PathPrefix(`/node`)
      - traefik.http.routers.internet-node-http-router.middlewares=prefix-stripper
      # Internet HTTPS
      - traefik.http.routers.internet-node-https-router.tls=true
      - traefik.http.routers.internet-node-https-router.tls.certresolver=raspiresolver
      - traefik.http.routers.internet-node-https-router.entrypoints=internet-https-entry
      - traefik.http.routers.internet-node-https-router.rule=Host(`raspi.alanas-j.site`) && PathPrefix(`/node`)
      - traefik.http.routers.internet-node-https-router.middlewares=prefix-stripper
    networks:
      - service_network
    restart: unless-stopped
