# You're expected to run a reverse-proxy in front of Loki leveraging
# Eg. mTLS or TLS + BasicAuth
# auth_enabled: true checks for a X-Scope-OrgID header
auth_enabled: false 

schema_config:
  configs:
    - from: 2025-03-24 
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h # The partition period, the index data is split in intervals.

storage_config:
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache

compactor:
  working_directory: /loki/retention
  retention_enabled: true
  delete_request_store: filesystem

limits_config:
  retention_period: 336h # 14 Days Log Retention (config used by compactor)

analytics:
  reporting_enabled: false

server:   
  http_listen_port: 3100   
  log_level: info 
  # Can setup TLS + more via config:
  # https://grafana.com/docs/loki/latest/configure/#server
