global:
    checkNewVersion: false
    sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  
entryPoints:
  internet-http-entry:
    address: ":20080"
    http:
     redirections:
       entryPoint:
         to: https-entry
         scheme: https
  internet-https-entry:
    address: ":200443"

  local-http-entry:
    address: ":80"
    http:
     redirections:
       entryPoint:
         to: https-entry
         scheme: https
  local-https-entry:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  raspiresolver:
    acme:
      storage: /var/traefik/certs/lets-encrypt-cert.json
      tlsChallenge: {}
      # Kept on timing out
      # dnsChallenge:
      #   provider: route53
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Testing API
